### ISSUE TITLE
Support fragments

### ISSUE THREAD

**Issue by andylizi** [turtlemay/jsx-dom#14]
https://reactjs.org/docs/fragments.html

I'm currently using something like
```ts
else if (child instanceof HTMLTemplateElement) {
    parent.appendChild(child.content);
}
else if (child instanceof HTMLElement) {
    parent.appendChild(child);
}
```
```ts
export const Fragment = 'template'
```
which seems to work alright.

**Comment by turtlemay** [comment]
I see what you're getting at but I'm not sure that implementation makes sense as template elements already work and this would change their outward behavior in a non-intuitive way (i.e. turning the JSX element into a document fragment instead of returning the template element directly which you can then work with using native APIs). But I agree that the React fragments should turn into native fragments.

**Comment by turtlemay** [comment]
I have implemented fragments as document fragments. c13df04934291de8ef9e4488949f4ce473b37063
